# Setting appropriate Application Security Groups is critical for a secure
# deployment. Change the value of the param below to "X" to acknowledge that
# once the Elastic Runtime deployment completes, you will review and set the
# appropriate application security groups.
# See https://docs.pivotal.io/pivotalcf/opsguide/app-sec-groups.html
security_acknowledgement: CHANGEME

pivnet_token: CHANGEME                  # Pivnet token for downloading resources from Pivnet. Find this token at https://network.pivotal.io/users/dashboard/edit-profile
opsman_major_minor_version: ^1\.12\..*$ # PCF Ops Manager minor version to track
ert_major_minor_version: ^1\.12\..*$    # PCF Elastic Runtime minor version to track
git_private_key:                        # Optional - if your git repo requires an SSH key.

# Errands to disable prior to deploying ERT
# Valid values:
#   all
#   none
#   "" (empty string - equivalent to none)
#   Any combination of the following, separated by comma:
#     smoke-tests
#     push-apps-manager
#     notifications
#     notifications-ui
#     push-pivotal-account
#     autoscaling
#     autoscaling-register-broker
#     nfsbrokerpush
ert_errands_to_disable:       # Comma-separated list of errand names to disable before deploy

# vCenter configuration
vcenter_host: CHANGEME             # vCenter host or IP
vcenter_usr: CHANGEME              # vCenter username. If user is tied to a domain, then escape the \, example `domain\\user`
vcenter_pwd: CHANGEME              # vCenter password
vcenter_datacenter: CHANGEME       # vCenter datacenter
vcenter_insecure: CHANGEME         # vCenter skip TLS cert validation; enter `1` to disable cert verification, `0` to enable verification
vcenter_ca_cert: CHANGEME          # vCenter CA cert at the API endpoint; enter a value if `vcenter_insecure: 0`

# Ops Manager VM configuration
om_vm_host:                           # Optional - vCenter host to deploy Ops Manager in
om_vm_folder:                         # Optional - vCenter folder to put Ops Manager in
vcenter_datastore: CHANGEME           # vCenter datastore name to deploy Ops Manager in
opsman_domain_or_ip_address: CHANGEME # FQDN to access Ops Manager without protocol (will use https), ex: opsmgr.example.com

# Either opsman_client_id/opsman_client_secret or opsman_admin_username/opsman_admin_password needs to be specified
opsman_client_id: CHANGEME            # Client ID for Ops Manager admin account
opsman_client_secret: CHANGEME        # Client Secret for Ops Manager admin account
opsman_admin_username: CHANGEME       # Username for Ops Manager admin account
opsman_admin_password: CHANGEME       # Password for Ops Manager admin account

opsman_ssh_password: CHANGEME         # SSH password for Ops Manager (ssh user is ubuntu)
om_decryption_pwd: CHANGEME           # Decryption password for Ops Manager exported settings
om_ntp_servers: CHANGEME              # Comma-separated list of NTP Servers
om_dns_servers: CHANGEME              # Comma-separated list of DNS Servers
om_gateway: CHANGEME                  # Gateway for Ops Manager network
om_netmask: CHANGEME                  # Netmask for Ops Manager network
om_ip: CHANGEME                       # IP to assign to Ops Manager VM
om_vm_network: CHANGEME               # vCenter network name to use to deploy Ops Manager in
om_vm_name: CHANGEME                  # Name to use for Ops Manager VM
opsman_disk_type: "thin"              # Disk type for Ops Manager VM (thick|thin)
om_vm_power_state: true               # Whether to power on Ops Manager VM after creation

# vCenter Cluster or Resource Pool to use to deploy Ops Manager.
# Possible formats:
#   cluster:       /<Data Center Name>/host/<Cluster Name>
#   resource pool: /<Data Center Name>/host/<Cluster Name>/Resources/<Resource Pool Name>
om_resource_pool: CHANGEME

ephemeral_storage_names: CHANGEME  # Ephemeral Storage names in vCenter for use by PCF
persistent_storage_names: CHANGEME # Persistent Storage names in vCenter for use by PCF

bosh_vm_folder: "pcf_vms"                 # vSphere datacenter folder (such as pcf_vms) where VMs will be placed
bosh_template_folder: "pcf_templates"     # vSphere datacenter folder (such as pcf_templates) where templates will be placed
bosh_disk_path: "pcf_disk"                # vSphere datastore folder (such as pcf_disk) where attached disk images will be created

# Optional PEM-encoded certificates to add to BOSH director
trusted_certificates:         # Trusted certificates to be deployed along with all VM's provisioned by BOSH
vm_disk_type: "thick"         # Disk type for BOSH provisioned VM. (thick|thin)

# AZ configuration for Ops Director
az_1_name: CHANGEME                    # Logical name of availability zone. No spaces or special characters.
az_1_cluster_name: CHANGEME            # Name of cluster in vCenter for AZ1
az_1_rp_name: CHANGEME                 # Resource pool name in vCenter for AZ1
az_2_name: CHANGEME                    # Logical name of availability zone. No spaces or special characters.
az_2_cluster_name: CHANGEME            # Name of cluster in vCenter for AZ2
az_2_rp_name: CHANGEME                 # Resource pool name in vCenter for AZ2
az_3_name: CHANGEME                    # Logical name of availability zone. No spaces or special characters.
az_3_cluster_name: CHANGEME            # Name of cluster in vCenter for AZ3
az_3_rp_name: CHANGEME                 # Resource pool name in vCenter for AZ3

ntp_servers: CHANGEME                  # Comma-separated list of NTP servers to use for VMs deployed by BOSH
ops_dir_hostname:                      # Optional DNS name for Ops Director. Should be reachable from all networks.
enable_vm_resurrector: true            # Whether to enable BOSH VM resurrector
max_threads: 30                        # Max threads count for deploying VMs

# Network configuration for Ops Director
icmp_checks_enabled: true     # Enable or disable ICMP checks

infra_network_name: "INFRASTRUCTURE"
infra_vsphere_network: CHANGEME        # vCenter Infrastructure network name
infra_nw_cidr: CHANGEME                # Infrastructure network CIDR, ex: 10.0.0.0/22
infra_excluded_range: CHANGEME         # Infrastructure network exclusion range
infra_nw_dns: CHANGEME                 # Infrastructure network DNS
infra_nw_gateway: CHANGEME             # Infrastructure network Gateway
infra_nw_azs: CHANGEME                 # Comma separated list of AZ's to be associated with this network

nsx_networking_enabled: false # (true|false) to use nsx networking feature
nsx_address:                  # address of nsx
nsx_username:                 # username for nsx access
nsx_password:                 # password for nsx access
nsx_ca_certificate:           # cert for nsx

deployment_network_name: "DEPLOYMENT"
deployment_vsphere_network: CHANGEME   # vCenter Deployment network name
deployment_nw_cidr: CHANGEME           # Deployment network CIDR, ex: 10.0.0.0/22
deployment_excluded_range: CHANGEME    # Deployment network exclusion range
deployment_nw_dns: CHANGEME            # Deployment network DNS
deployment_nw_gateway: CHANGEME        # Deployment network Gateway
deployment_nw_azs: CHANGEME            # Comma separated list of AZ's to be associated with this network

services_network_name: "SERVICES"
is_service_network: CHANGEME           # Required select service network option in Ops man true or false
services_vsphere_network: CHANGEME     # vCenter Services network name
services_nw_cidr: CHANGEME             # Services network CIDR, ex: 10.0.0.0/22
services_excluded_range: CHANGEME      # Services network exclusion range
services_nw_dns: CHANGEME              # Services network DNS
services_nw_gateway: CHANGEME          # Services network Gateway
services_nw_azs: CHANGEME              # Comma separated list of AZ's to be associated with this network

dynamic_services_network_name: "DYNAMIC-SERVICES"
dynamic_services_vsphere_network: CHANGEME     # vCenter Dynamic Services network name
dynamic_services_nw_cidr: CHANGEME             # Dynamic Services network CIDR, ex: 10.0.0.0/22
dynamic_services_excluded_range: CHANGEME      # Dynamic Services network exclusion range
dynamic_services_nw_dns: CHANGEME              # Dynamic Services network DNS
dynamic_services_nw_gateway: CHANGEME          # Dynamic Services network Gateway
dynamic_services_nw_azs: CHANGEME              # Comma separated list of AZ's to be associated with this network

ert_singleton_job_az: CHANGEME         # AZ to use for deployment of ERT Singleton jobs

loggregator_endpoint_port:    # Loggegrator Port. Default is 443
company_name:                 # Company Name for Apps Manager
company_proxy_domain:         # If set to a non-empty string, bypass DNS when uploading stemcells to Ops Manager

container_networking_nw_cidr: 10.255.0.0/16 # c2c networking network cidr

## Syslog endpoint configuration goes here
# Optional. If syslog_host is specified, syslog_port, syslog_protocol,
# syslog_drain_buffer_size, and enable_security_event_logging must be set.
syslog_host:
syslog_port:
syslog_protocol:
enable_security_event_logging: false
syslog_drain_buffer_size: 10000

## Wildcard domain certs go here
# Optional. Will be generated if blank.
ssl_cert:
ssl_private_key:
saml_ssl_cert:
saml_ssl_private_key:

haproxy_forward_tls: enable # If enabled HAProxy will forward all requests to the router over TLS (enable|disable)
haproxy_backend_ca:         # Required if haproxy_forward_tls is enabled - HAProxy will use the CA provided to verify the certificates provided by the router.

# An ordered, colon-delimited list of Golang supported TLS cipher suites in OpenSSL format.
# Operators should verify that these are supported by any clients or downstream components that will initiate TLS handshakes with the Router/HAProxy.
# The recommended settings are filled in below, change as necessary.
router_tls_ciphers: "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"
haproxy_tls_ciphers: "DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"

# Disable HTTP on gorouters (true|false)
disable_http_proxy: false

## TCP routing and routing services
tcp_routing: disable                    # Enable/disable TCP routing (enable|disable)
tcp_routing_ports:                      # A comma-separated list of ports and hyphen-separated port ranges, e.g. 52135,34000-35000,23478
route_services: disable                 # Enable/disable route services (enable|disable)
ignore_ssl_cert_verification: false     # Whether to disable SSL cert verification for this environment
garden_network_pool_cidr: 10.254.0.0/22 # Only change this if you need to avoid address collision with a third-party service on the same subnet.
garden_network_mtu: 1454                # Applications Network Maximum Transmission Unit bytes

# If smtp_address is configured, smtp_from, smtp_port, smtp_user, smtp_pwd,
# smtp_enable_starttls_auto, and smtp_auth_mechanism must also be set.
smtp_address:
smtp_from:
smtp_port:
smtp_user:
smtp_pwd:
smtp_enable_starttls_auto: true
smtp_auth_mechanism: # (none|plain|cram-md5)

## Authentication type needed. SAML is not presently supported.
authentication_mode: internal # (internal|ldap) If ldap, specify ldap configuration below.
ldap_url:
ldap_user:
ldap_pwd:
search_base:
search_filter:
group_search_base:
group_search_filter:
mail_attribute_name:
first_name_attribute:
last_name_attribute:

## Deployment domain names
system_domain: CHANGEME # e.g. system.pcf.example.com
apps_domain: CHANGEME   # e.g. apps.pcf.example.com

skip_cert_verify: false       # If true, disable SSL certificate verification for this environment.

disable_insecure_cookies: false # If true, disable insecure cookies on the router.

default_quota_memory_limit_mb: 10240
default_quota_max_number_services: 1000
allow_app_ssh_access: false             # Whether to allow SSH access to application instances

# Request timeout for gorouter
router_request_timeout_in_seconds: 900

ha_proxy_ips:           # Comma-separated list of static IPs
router_static_ips:      # Comma-separated list of static IPs
tcp_router_static_ips:  # Comma-separated list of static IPs
ssh_static_ips:         # Comma-separated list of static IPs
mysql_static_ips:       # Comma-separated list of static IPs

mysql_monitor_email:    # Email address to receive MySQL monitor notifications
mysql_backups: disable   # Whether to enable MySQL backups. (disable|s3|scp)

# SCP backup config params (leave empty values if you're not using scp)
mysql_backups_scp_server:
mysql_backups_scp_port:
mysql_backups_scp_user:
mysql_backups_scp_key:
mysql_backups_scp_destination:
mysql_backups_scp_cron_schedule:

# S3 backup config params (leave empty values if you're not using s3)
mysql_backups_s3_endpoint_url:
mysql_backups_s3_bucket_name:
mysql_backups_s3_bucket_path:
mysql_backups_s3_access_key_id:
mysql_backups_s3_secret_access_key:
mysql_backups_s3_cron_schedule:

## Default resource configuration
## these resources can take any parameter made available in
## the ops manager API ( https://<your-ops-man/docs#configuring-resources-for-a-job )
consul_server_instances: 3
nats_instances: 2
nfs_server_instances: 1
mysql_proxy_instances: 2
mysql_instances: 3
backup_prepare_instances: 0
diego_database_instances: 3
uaa_instances: 2
cloud_controller_instances: 2
ha_proxy_instances: 0
router_instances: 3
mysql_monitor_instances: 1
clock_global_instances: 1
cloud_controller_worker_instances: 2
diego_brain_instances: 3
diego_cell_instances: 3
loggregator_traffic_controller_instances: 3
syslog_adapter_instances: 3
doppler_instances: 3
tcp_router_instances: 0

# Whether or not the ERT VMs are internet connected.
internet_connected: true

# leave nsx fields empty if you are not leveraging the nsx features for a given component
tcp_router_nsx_security_group:
tcp_router_nsx_lb_edge_name:
tcp_router_nsx_lb_pool_name:
tcp_router_nsx_lb_security_group:
tcp_router_nsx_lb_port:
router_nsx_security_group:
router_nsx_lb_edge_name:
router_nsx_lb_pool_name:
router_nsx_lb_security_group:
router_nsx_lb_port:
diego_brain_nsx_security_group:
diego_brain_nsx_lb_edge_name:
diego_brain_nsx_lb_pool_name:
diego_brain_nsx_lb_security_group:
diego_brain_nsx_lb_port:
mysql_nsx_security_group:
mysql_nsx_lb_edge_name:
mysql_nsx_lb_pool_name:
mysql_nsx_lb_security_group:
mysql_nsx_lb_port:
