pivnet_token: CHANGEME                  # Pivnet token for downloading resources from Pivnet. Find this token at https://network.pivotal.io/users/dashboard/edit-profile
opsman_major_minor_version: ^1\.12\..*$ # PCF Ops Manager minor version to track
ert_major_minor_version: ^1\.12\..*$    # PCF Elastic Runtime minor version to track
git_private_key:                        # Optional - if your git repo requires an SSH key.

# Errands to disable prior to deploying ERT
# Valid values:
#   all
#   none
#   "" (empty string - equivalent to none)
#   Any combination of the following, separated by comma:
#     smoke-tests
#     push-apps-manager
#     notifications
#     notifications-ui
#     push-pivotal-account
#     autoscaling
#     autoscaling-register-broker
#     nfsbrokerpush
ert_errands_to_disable:       # Comma-separated list of errand names to disable before deploy

# vCenter configuration
vcenter_host: CHANGEME             # vCenter host or IP
vcenter_usr: CHANGEME              # vCenter username. If user is tied to a domain, then escape the \, example `domain\\user`
vcenter_pwd: CHANGEME              # vCenter password
vcenter_datacenter: CHANGEME       # vCenter datacenter
vcenter_insecure: CHANGEME         # vCenter skip TLS cert validation; enter `1` to disable cert verification, `0` to enable verification
vcenter_ca_cert: CHANGEME          # vCenter CA cert at the API endpoint; enter a value if `vcenter_insecure: 0`

# Ops Manager VM configuration
om_vm_host:                           # Optional - vCenter host to deploy Ops Manager in
om_vm_folder:                         # Optional - vCenter folder to put Ops Manager in
vcenter_datastore: CHANGEME           # vCenter datastore name to deploy Ops Manager in
opsman_domain_or_ip_address: CHANGEME # FQDN to access Ops Manager without protocol (will use https), ex: opsmgr.example.com

# Either opsman_client_id/opsman_client_secret or opsman_admin_username/opsman_admin_password needs to be specified
opsman_client_id: CHANGEME            # Client ID for Ops Manager admin account
opsman_client_secret: CHANGEME        # Client Secret for Ops Manager admin account
opsman_admin_username: CHANGEME       # Username for Ops Manager admin account
opsman_admin_password: CHANGEME       # Password for Ops Manager admin account

opsman_ssh_password: CHANGEME         # SSH password for Ops Manager (ssh user is ubuntu)
om_decryption_pwd: CHANGEME           # Decryption password for Ops Manager exported settings
om_ntp_servers: CHANGEME              # Comma-separated list of NTP Servers
om_dns_servers: CHANGEME              # Comma-separated list of DNS Servers
om_gateway: CHANGEME                  # Gateway for Ops Manager network
om_netmask: CHANGEME                  # Netmask for Ops Manager network
om_ip: CHANGEME                       # IP to assign to Ops Manager VM
om_vm_network: CHANGEME               # vCenter network name to use to deploy Ops Manager in
om_vm_name: CHANGEME                  # Name to use for Ops Manager VM
opsman_disk_type: "thin"              # Disk type for Ops Manager VM (thick|thin)
om_vm_power_state: true               # Whether to power on Ops Manager VM after creation

# vCenter Cluster or Resource Pool to use to deploy Ops Manager.
# Possible formats:
#   cluster:       /<Data Center Name>/host/<Cluster Name>
#   resource pool: /<Data Center Name>/host/<Cluster Name>/Resources/<Resource Pool Name>
om_resource_pool: CHANGEME

ephemeral_storage_names: CHANGEME  # Ephemeral Storage names in vCenter for use by PCF
persistent_storage_names: CHANGEME # Persistent Storage names in vCenter for use by PCF

bosh_vm_folder: "pcf_vms"                 # vSphere datacenter folder (such as pcf_vms) where VMs will be placed
bosh_template_folder: "pcf_templates"     # vSphere datacenter folder (such as pcf_templates) where templates will be placed
bosh_disk_path: "pcf_disk"                # vSphere datastore folder (such as pcf_disk) where attached disk images will be created

# Optional PEM-encoded certificates to add to BOSH director
trusted_certificates:         # Trusted certificates to be deployed along with all VM's provisioned by BOSH
vm_disk_type: "thick"         # Disk type for BOSH provisioned VM. (thick|thin)

# AZ configuration for Ops Director
az_1_name: CHANGEME                    # Logical name of availability zone. No spaces or special characters.
az_1_cluster_name: CHANGEME            # Name of cluster in vCenter for AZ1
az_1_rp_name: CHANGEME                 # Resource pool name in vCenter for AZ1
az_2_name: CHANGEME                    # Logical name of availability zone. No spaces or special characters.
az_2_cluster_name: CHANGEME            # Name of cluster in vCenter for AZ2
az_2_rp_name: CHANGEME                 # Resource pool name in vCenter for AZ2
az_3_name: CHANGEME                    # Logical name of availability zone. No spaces or special characters.
az_3_cluster_name: CHANGEME            # Name of cluster in vCenter for AZ3
az_3_rp_name: CHANGEME                 # Resource pool name in vCenter for AZ3

ntp_servers: CHANGEME                  # Comma-separated list of NTP servers to use for VMs deployed by BOSH
ops_dir_hostname:                      # Optional DNS name for Ops Director. Should be reachable from all networks.
enable_vm_resurrector: true            # Whether to enable BOSH VM resurrector
max_threads: 30                        # Max threads count for deploying VMs

# Network configuration for Ops Director
icmp_checks_enabled: true     # Enable or disable ICMP checks

infra_network_name: "INFRASTRUCTURE"
infra_vsphere_network: CHANGEME        # vCenter Infrastructure network name
infra_nw_cidr: CHANGEME                # Infrastructure network CIDR, ex: 10.0.0.0/22
infra_excluded_range: CHANGEME         # Infrastructure network exclusion range
infra_nw_dns: CHANGEME                 # Infrastructure network DNS
infra_nw_gateway: CHANGEME             # Infrastructure network Gateway
infra_nw_azs: CHANGEME                 # Comma separated list of AZ's to be associated with this network

nsx_networking_enabled: false # (true|false) to use nsx networking feature
nsx_address:                  # address of nsx
nsx_username:                 # username for nsx access
nsx_password:                 # password for nsx access
nsx_ca_certificate:           # cert for nsx

deployment_network_name: "DEPLOYMENT"
deployment_vsphere_network: CHANGEME   # vCenter Deployment network name
deployment_nw_cidr: CHANGEME           # Deployment network CIDR, ex: 10.0.0.0/22
deployment_excluded_range: CHANGEME    # Deployment network exclusion range
deployment_nw_dns: CHANGEME            # Deployment network DNS
deployment_nw_gateway: CHANGEME        # Deployment network Gateway
deployment_nw_azs: CHANGEME            # Comma separated list of AZ's to be associated with this network

services_network_name: "SERVICES"
is_service_network: CHANGEME           # Required select service network option in Ops man true or false
services_vsphere_network: CHANGEME     # vCenter Services network name
services_nw_cidr: CHANGEME             # Services network CIDR, ex: 10.0.0.0/22
services_excluded_range: CHANGEME      # Services network exclusion range
services_nw_dns: CHANGEME              # Services network DNS
services_nw_gateway: CHANGEME          # Services network Gateway
services_nw_azs: CHANGEME              # Comma separated list of AZ's to be associated with this network

dynamic_services_network_name: "DYNAMIC-SERVICES"
dynamic_services_vsphere_network: CHANGEME     # vCenter Dynamic Services network name
dynamic_services_nw_cidr: CHANGEME             # Dynamic Services network CIDR, ex: 10.0.0.0/22
dynamic_services_excluded_range: CHANGEME      # Dynamic Services network exclusion range
dynamic_services_nw_dns: CHANGEME              # Dynamic Services network DNS
dynamic_services_nw_gateway: CHANGEME          # Dynamic Services network Gateway
dynamic_services_nw_azs: CHANGEME              # Comma separated list of AZ's to be associated with this network

company_proxy_domain:         # If set to a non-empty string, bypass DNS when uploading stemcells to Ops Manager

# The CF Properties configuration (in yaml) to provide to Ops Manager
cf_properties: |
  CHANGEME

# The CF Network configuration (in yaml) to provide to Ops Manager
cf_network: |
  CHANGEME

# The CF Resources configuration (in yaml) to provide to Ops Manager
cf_resources: |
  CHANGEME
